const alphabetDefinition = [
  {
    key: 'ani',
    longName: 'ani',
    unicode: 'ა',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=2',
  },
  {
    key: 'bani',
    longName: 'bani',
    unicode: 'ბ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=4',
  },
  {
    key: 'gani',
    longName: 'gani',
    unicode: 'გ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=6',
  },
  {
    key: 'doni',
    longName: 'doni',
    unicode: 'დ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=8',
  },
  {
    key: 'eni',
    longName: 'eni',
    unicode: 'ე',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=10',
  },
  {
    key: 'vini',
    longName: 'vini',
    unicode: 'ვ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=12',
  },
  {
    key: 'zeni',
    longName: 'zeni',
    unicode: 'ზ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=13',
  },
  {
    key: 'tani',
    longName: 'tani',
    unicode: 'თ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=16',
  },
  {
    key: 'ini',
    longName: 'ini',
    unicode: 'ი',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=18',
  },
  {
    key: 'k_ani',
    longName: 'k\'ani',
    unicode: 'კ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=20',
  },
  {
    key: 'lasi',
    longName: 'lasi',
    unicode: 'ლ',
    hasAlternativeForm: true,
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=22',
  },
  {
    key: 'mani',
    longName: 'mani',
    unicode: 'მ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=25',
  },
  {
    key: 'nari',
    longName: 'nari',
    unicode: 'ნ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=27',
  },
  {
    key: 'oni',
    longName: 'oni',
    unicode: 'ო',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=29',
  },
  {
    key: 'p_ari',
    longName: 'p\'ari',
    unicode: 'პ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=31',
  },
  {
    key: 'zhani',
    longName: 'zhani',
    unicode: 'ჟ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=33',
  },
  {
    key: 'rae',
    longName: 'rae',
    unicode: 'რ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=35',
  },
  {
    key: 'sani',
    longName: 'sani',
    unicode: 'ს',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=37',
  },
  {
    key: 't_ari',
    longName: 't\'ari',
    unicode: 'ტ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=39',
  },
  {
    key: 'uni',
    longName: 'uni',
    unicode: 'უ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=41',
  },
  {
    key: 'pari',
    longName: 'pari',
    unicode: 'ფ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=43',
  },
  {
    key: 'kani',
    longName: 'kani',
    unicode: 'ქ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=45',
  },
  {
    key: 'ghani',
    longName: 'ghani',
    unicode: 'ღ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=48',
  },
  {
    key: 'q_ari',
    longName: 'q\'ari',
    unicode: 'ყ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=50',
  },
  {
    key: 'shini',
    longName: 'shini',
    unicode: 'შ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=52',
  },
  {
    key: 'chini',
    longName: 'chini',
    unicode: 'ჩ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=54',
  },
  {
    key: 'tsani',
    longName: 'tsani',
    unicode: 'ც',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=56',
  },
  {
    key: 'dzili',
    longName: 'dzili',
    unicode: 'ძ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=58',
  },
  {
    key: 'ts_ili',
    longName: 'ts\'ili',
    unicode: 'წ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=60',
  },
  {
    key: 'ch_ari',
    longName: 'ch\'ari',
    unicode: 'ჭ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=62',
  },
  {
    key: 'khani',
    longName: 'khani',
    unicode: 'ხ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=65',
  },
  {
    key: 'jani',
    longName: 'jani',
    unicode: 'ჯ',
    hasAlternafiveForm: true,
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=67',
  },
  {
    key: 'hae',
    longName: 'hae',
    unicode: 'ჰ',
    pronunciation: 'https://www.youtube.com/watch?v=uCuv-7trJVk#t=69',
  },
];

export default alphabetDefinition;
